# Generated by Django 3.0.8 on 2021-03-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_follow_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='image/default_img.jpg', upload_to='image'),
        ),
    ]
