# Generated by Django 3.0.8 on 2021-03-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210327_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='can_comment',
            field=models.BooleanField(default=True),
        ),
    ]
